### ISSUE TITLE
No Done jobs

### ISSUE THREAD

**Issue by makorne** [geofmureithi/apalis#48]
Hi

I test apalis (mysql backend)  with 2 workers and consistently add new jobs.

Tens of jobs is done but in database jobs table  is 2 jobs only.
Their id is changing - but no one job saved as done.
Why?

![2JobsApalis_Screenshot_2023-02-04_18-40-49](https://user-images.githubusercontent.com/26540498/216766684-3ed2c055-768c-4dcd-ab99-5439c283bbe9.png)

**Comment by geofmureithi** [comment]
Mysql uses `FOR UPDATE` which might have locked some rows.

**Comment by makorne** [comment]
No one of 100 jobs is stated as done in db.

So this is the Apalis bug? 
Or it is must be stated in Apalis docs: " "with mysql cant to work normal"?

**Comment by dlen** [comment]
Hi, I'm very late to the conversation but I think the problem is the ON DELETE CASCADE on the jobs table. https://github.com/geofmureithi/apalis/blob/master/packages/apalis-sql/migrations/mysql/20220530084123_jobs_workers.sql#L29

Getting rid of that would list the done jobs but it will require some cleanup at some point.

**Comment by dlen** [comment]
Hey I think the problem is related with this line: https://github.com/geofmureithi/apalis/blob/master/packages/apalis-sql/src/mysql.rs#L180 

Using replace with a foreign key in mysql will force the deletion of all the child rows.  I have a simple fork with a fix based on `INSERT` with `UPDATE ON DUPLICATE` that is working for me. I can send a PR if you want it. https://github.com/dlen/apalis/blob/master/packages/apalis-sql/src/mysql.rs#L180

**Comment by geofmureithi** [comment]
@dlen Please do!
